/** @format */

export const pricingPlans = [
  {
    id: "plus",
    name: "Plus",
    tagline: "Perfect to get started",
    price: 99,
    credits: 50,
    notesCount: 5,
    features: [
      "50 AI credits",
      "~5 full note generations",
      "PDF export",
      "Revision mode",
      "History saved for 30 days",
    ],
    accent: "from-blue-500/20 to-cyan-500/10",
    border: "border-blue-400/25",
    button: "bg-white/10 hover:bg-white/15 border border-white/15 text-white",
    popular: false,
  },
  {
    id: "trending",
    name: "Most Trending",
    tagline: "Best value for serious prep",
    price: 199,
    credits: 150,
    notesCount: 15,
    features: [
      "150 AI credits",
      "~15 full note generations",
      "PDF export + diagrams",
      "Quick revision mode",
      "Priority generation speed",
      "Unlimited history access",
    ],
    accent: "from-purple-500/30 via-pink-500/20 to-indigo-500/10",
    border: "border-purple-400/50",
    button:
      "bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-white shadow-lg shadow-purple-500/30 hover:opacity-90",
    popular: true,
    badge: "Most Popular",
  },
  {
    id: "premium",
    name: "Premium",
    tagline: "For power users & toppers",
    price: 399,
    credits: 500,
    notesCount: 50,
    features: [
      "500 AI credits",
      "~50 full note generations",
      "Everything in Most Trending",
      "Charts & diagram generation",
      "Early access to new features",
      "Priority support",
    ],
    accent: "from-amber-500/20 to-orange-500/10",
    border: "border-amber-400/30",
    button: "bg-amber-500/20 hover:bg-amber-500/30 border border-amber-400/40 text-amber-100",
    popular: false,
  },
];
